In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('weatherAUS.csv')

In [3]:
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   
3          NE           24.0         SE  ...        16.0       1017.6   
4           W           41.0        ENE  ...        33.0       1010.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   
3       1012.8       NaN       NaN     18.1     26.5         No      1.0   
4       1006.0       7.0       8.0     17.8     29.7         No      0.2   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 24 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
Date             142193 non-null object
Location         142193 non-null object
MinTemp          141556 non-null float64
MaxTemp          141871 non-null float64
Rainfall         140787 non-null float64
Evaporation      81350 non-null float64
Sunshine         74377 non-null float64
WindGustDir      132863 non-null object
WindGustSpeed    132923 non-null float64
WindDir9am       132180 non-null object
WindDir3pm       138415 non-null object
WindSpeed9am     140845 non-null float64
WindSpeed3pm     139563 non-null float64
Humidity9am      140419 non-null float64
Humidity3pm      138583 non-null float64
Pressure9am      128179 non-null float64
Pressure3pm      128212 non-null float64
Cloud9am         88536 non-null float64
Cloud3pm         85099 non-null float64
Temp9am          141289 non-null float64
Temp3pm          139467 non-null float64
RainToday        140787 non-null obje

In [5]:
df['Location'].unique()

array(['Albury', 'BadgerysCreek', 'Cobar', 'CoffsHarbour', 'Moree',
       'Newcastle', 'NorahHead', 'NorfolkIsland', 'Penrith', 'Richmond',
       'Sydney', 'SydneyAirport', 'WaggaWagga', 'Williamtown',
       'Wollongong', 'Canberra', 'Tuggeranong', 'MountGinini', 'Ballarat',
       'Bendigo', 'Sale', 'MelbourneAirport', 'Melbourne', 'Mildura',
       'Nhil', 'Portland', 'Watsonia', 'Dartmoor', 'Brisbane', 'Cairns',
       'GoldCoast', 'Townsville', 'Adelaide', 'MountGambier', 'Nuriootpa',
       'Woomera', 'Albany', 'Witchcliffe', 'PearceRAAF', 'PerthAirport',
       'Perth', 'SalmonGums', 'Walpole', 'Hobart', 'Launceston',
       'AliceSprings', 'Darwin', 'Katherine', 'Uluru'], dtype=object)

In [6]:
df_syd=df[df['Location']=='Sydney']
df_cbr=df[df['Location']=='Canberra']
df_mlb=df[df['Location']=='Melbourne']
df_adl=df[df['Location']=='Adelaide']
df_drw=df[df['Location']=='Darwin']

In [7]:
df1=pd.concat([df_syd,df_cbr,df_mlb,df_adl,df_drw],axis=0)
df1.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
29497  2008-02-01   Sydney     19.5     22.4      15.6          6.2       0.0   
29498  2008-02-02   Sydney     19.5     25.6       6.0          3.4       2.7   
29499  2008-02-03   Sydney     21.6     24.5       6.6          2.4       0.1   
29500  2008-02-04   Sydney     20.2     22.8      18.8          2.2       0.0   
29501  2008-02-05   Sydney     19.7     25.7      77.4          NaN       0.0   

      WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
29497         NaN            NaN          S  ...        84.0       1017.6   
29498         NaN            NaN          W  ...        73.0       1017.9   
29499         NaN            NaN        ESE  ...        86.0       1016.7   
29500         NaN            NaN        NNE  ...        90.0       1014.2   
29501         NaN            NaN        NNE  ...        74.0       1008.3   

       Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
29497       1017.4       8.0       8.0     20.7     20.9        Yes      6.0   
29498       1016.4       7.0       7.0     22.4     24.8        Yes      6.6   
29499       1015.6       7.0       8.0     23.5     23.0        Yes     18.8   
29500       1011.8       8.0       8.0     21.4     20.9        Yes     77.4   
29501       1004.8       8.0       8.0     22.5     25.5        Yes      1.6   

       RainTomorrow  
29497           Yes  
29498           Yes  
29499           Yes  
29500           Yes  
29501           Yes  

[5 rows x 24 columns]

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15472 entries, 29497 to 139112
Data columns (total 24 columns):
Date             15472 non-null object
Location         15472 non-null object
MinTemp          15460 non-null float64
MaxTemp          15464 non-null float64
Rainfall         15243 non-null float64
Evaporation      12331 non-null float64
Sunshine         12154 non-null float64
WindGustDir      14025 non-null object
WindGustSpeed    14031 non-null float64
WindDir9am       14555 non-null object
WindDir3pm       15182 non-null object
WindSpeed9am     15209 non-null float64
WindSpeed3pm     15217 non-null float64
Humidity9am      15388 non-null float64
Humidity3pm      15433 non-null float64
Pressure9am      15218 non-null float64
Pressure3pm      15221 non-null float64
Cloud9am         10343 non-null float64
Cloud3pm         10097 non-null float64
Temp9am          15444 non-null float64
Temp3pm          15451 non-null float64
RainToday        15243 non-null object
RISK_MM     

In [9]:
df_use=df1[['MinTemp','MaxTemp','WindGustSpeed','Humidity3pm','Pressure3pm','Location','RainTomorrow']]

In [10]:
df_use.head()

MinTemp  MaxTemp  WindGustSpeed  Humidity3pm  Pressure3pm Location  \
29497     19.5     22.4            NaN         84.0       1017.4   Sydney   
29498     19.5     25.6            NaN         73.0       1016.4   Sydney   
29499     21.6     24.5            NaN         86.0       1015.6   Sydney   
29500     20.2     22.8            NaN         90.0       1011.8   Sydney   
29501     19.7     25.7            NaN         74.0       1004.8   Sydney   

      RainTomorrow  
29497          Yes  
29498          Yes  
29499          Yes  
29500          Yes  
29501          Yes

In [11]:
df_use.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15472 entries, 29497 to 139112
Data columns (total 7 columns):
MinTemp          15460 non-null float64
MaxTemp          15464 non-null float64
WindGustSpeed    14031 non-null float64
Humidity3pm      15433 non-null float64
Pressure3pm      15221 non-null float64
Location         15472 non-null object
RainTomorrow     15472 non-null object
dtypes: float64(5), object(2)
memory usage: 967.0+ KB


In [12]:
df_use['MinTemp'].fillna(df['Temp9am'],inplace=True)
df_use['MaxTemp'].fillna(df['Temp3pm'],inplace=True)
df_use['WindGustSpeed'].fillna(round(df_use['WindGustSpeed'].mean(),1),inplace=True)
df_use['Humidity3pm'].fillna(round(df_use['Humidity3pm'].mean(),1),inplace=True)
df_use['Pressure3pm'].fillna(round(df_use['Pressure3pm'].mean(),1),inplace=True)
df_use.info()

C:\Users\Cornelis\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


<class 'pandas.core.frame.DataFrame'>
Int64Index: 15472 entries, 29497 to 139112
Data columns (total 7 columns):
MinTemp          15465 non-null float64
MaxTemp          15471 non-null float64
WindGustSpeed    15472 non-null float64
Humidity3pm      15472 non-null float64
Pressure3pm      15472 non-null float64
Location         15472 non-null object
RainTomorrow     15472 non-null object
dtypes: float64(5), object(2)
memory usage: 967.0+ KB


In [13]:
df_use['TempDiv']=df_use['MaxTemp']-df_use['MinTemp']

C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [14]:
df_use['Humidity']=df_use['Humidity3pm']
df_use['Pressure']=df_use['Pressure3pm']

C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [15]:
df_use.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15472 entries, 29497 to 139112
Data columns (total 10 columns):
MinTemp          15465 non-null float64
MaxTemp          15471 non-null float64
WindGustSpeed    15472 non-null float64
Humidity3pm      15472 non-null float64
Pressure3pm      15472 non-null float64
Location         15472 non-null object
RainTomorrow     15472 non-null object
TempDiv          15465 non-null float64
Humidity         15472 non-null float64
Pressure         15472 non-null float64
dtypes: float64(8), object(2)
memory usage: 1.3+ MB


In [16]:
df_use.drop(columns=['MinTemp','MaxTemp','Humidity3pm','Pressure3pm'],inplace=True)

C:\Users\Cornelis\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [17]:
df_use.dropna(how='any',inplace=True)

C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [18]:
df_use.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15465 entries, 29497 to 139112
Data columns (total 6 columns):
WindGustSpeed    15465 non-null float64
Location         15465 non-null object
RainTomorrow     15465 non-null object
TempDiv          15465 non-null float64
Humidity         15465 non-null float64
Pressure         15465 non-null float64
dtypes: float64(4), object(2)
memory usage: 845.7+ KB


In [19]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df_use['RainTomorrow']=label.fit_transform(df_use['RainTomorrow'])
df_use['Location']=label.fit_transform(df_use['Location'])

C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [20]:
df_use.head()

WindGustSpeed  Location  RainTomorrow  TempDiv  Humidity  Pressure
29497           40.6         4             1      2.9      84.0    1017.4
29498           40.6         4             1      6.1      73.0    1016.4
29499           40.6         4             1      2.9      86.0    1015.6
29500           40.6         4             1      2.6      90.0    1011.8
29501           40.6         4             1      6.0      74.0    1004.8

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(df_use.drop(columns=['RainTomorrow']),df_use.RainTomorrow,test_size = 0.2)

In [22]:
X_train.shape,X_test.shape

((12372, 5), (3093, 5))

In [23]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report,confusion_matrix,log_loss,matthews_corrcoef
from sklearn.linear_model import LogisticRegression
pipe_knn = Pipeline([('std_scl', StandardScaler()), 
                    ('pca', PCA(n_components=2)),
                    ('knn', KNeighborsClassifier(n_neighbors=90))])

pipe_knn.fit(X_train, y_train)

print('Test Accuracy: %.3f' % pipe_knn.score(X_test, y_test))
train_pred=pipe_knn.predict(X_train)
knn_pred=pipe_knn.predict(X_test)
knn_predprob=pipe_knn.predict_proba(X_test)
print('Logloss: %.3f' %log_loss(y_test,knn_predprob))
print(classification_report(y_train,train_pred))
print(confusion_matrix(y_train,train_pred))
print(classification_report(y_test,knn_pred))
print(confusion_matrix(y_test,knn_pred))

Test Accuracy: 0.813
Logloss: 0.465
              precision    recall  f1-score   support

           0       0.82      0.96      0.89      9432
           1       0.71      0.35      0.47      2940

    accuracy                           0.81     12372
   macro avg       0.77      0.65      0.68     12372
weighted avg       0.80      0.81      0.79     12372

[[9009  423]
 [1913 1027]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.89      2364
           1       0.73      0.33      0.46       729

    accuracy                           0.81      3093
   macro avg       0.78      0.65      0.67      3093
weighted avg       0.80      0.81      0.79      3093

[[2272   92]
 [ 485  244]]


In [24]:
pipe_rfc = Pipeline([('std_scl', StandardScaler()), 
                    ('pca', PCA(n_components=2)),
                    ('rfc', RandomForestClassifier(n_estimators=100,criterion='gini',n_jobs=-1))])

pipe_rfc.fit(X_train, y_train)

print('Test Accuracy: %.3f' % pipe_rfc.score(X_test, y_test))
pred_rfc=pipe_rfc.predict(X_test)
predprob_rfc=pipe_rfc.predict_proba(X_test)
train_pred=pipe_rfc.predict(X_train)
print('Logloss: %.3f' %log_loss(y_test,predprob_rfc))
print(classification_report(y_train,train_pred))
print(confusion_matrix(y_train,train_pred))
print(classification_report(y_test,pred_rfc))
print(confusion_matrix(y_test,pred_rfc))

Test Accuracy: 0.790
Logloss: 0.688
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      9432
           1       1.00      1.00      1.00      2940

    accuracy                           1.00     12372
   macro avg       1.00      1.00      1.00     12372
weighted avg       1.00      1.00      1.00     12372

[[9431    1]
 [   2 2938]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87      2364
           1       0.58      0.39      0.47       729

    accuracy                           0.79      3093
   macro avg       0.70      0.65      0.67      3093
weighted avg       0.77      0.79      0.77      3093

[[2157  207]
 [ 444  285]]


In [25]:
pipe_xgb = Pipeline([('std_scl', StandardScaler()), 
                    ('pca', PCA(n_components=2)),
                    ('xgb', XGBClassifier(n_estimators=7,learning_rate=0.6,n_jobs=-1))])

pipe_xgb.fit(X_train, y_train)

print('Test Accuracy: %.3f' % pipe_xgb.score(X_test, y_test))
train_pred=pipe_xgb.predict(X_train)
pred_xgb=pipe_xgb.predict(X_test)
predprob_xgb=pipe_xgb.predict_proba(X_test)
print('Logloss: %.3f' %log_loss(y_test,predprob_xgb))
print(classification_report(y_train,train_pred))
print(confusion_matrix(y_train,train_pred))
print(classification_report(y_test,pred_xgb))
print(confusion_matrix(y_test,pred_xgb))

Test Accuracy: 0.813
Logloss: 0.421
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      9432
           1       0.70      0.37      0.48      2940

    accuracy                           0.81     12372
   macro avg       0.76      0.66      0.69     12372
weighted avg       0.80      0.81      0.79     12372

[[8967  465]
 [1850 1090]]
              precision    recall  f1-score   support

           0       0.83      0.95      0.89      2364
           1       0.70      0.36      0.48       729

    accuracy                           0.81      3093
   macro avg       0.77      0.66      0.68      3093
weighted avg       0.80      0.81      0.79      3093

[[2254  110]
 [ 467  262]]


In [26]:
pipe_log=Pipeline([('std_scl',StandardScaler()),
                  ('log',LogisticRegression())])

pipe_log.fit(X_train,y_train)
print('Test Accuracy: %.3f' % pipe_log.score(X_test, y_test))
train_pred=pipe_log.predict(X_train)
pred_log=pipe_log.predict(X_test)
predprob_log=pipe_log.predict_proba(X_test)
print('Logloss: %.3f' %log_loss(y_test,predprob_log))
print(classification_report(y_train,train_pred))
print(confusion_matrix(y_train,train_pred))
print(classification_report(y_test,pred_log))
print(confusion_matrix(y_test,pred_log))

C:\Users\Cornelis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Test Accuracy: 0.848
Logloss: 0.377
              precision    recall  f1-score   support

           0       0.86      0.95      0.90      9432
           1       0.74      0.49      0.59      2940

    accuracy                           0.84     12372
   macro avg       0.80      0.72      0.74     12372
weighted avg       0.83      0.84      0.82     12372

[[8917  515]
 [1504 1436]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91      2364
           1       0.77      0.50      0.61       729

    accuracy                           0.85      3093
   macro avg       0.82      0.73      0.76      3093
weighted avg       0.84      0.85      0.84      3093

[[2258  106]
 [ 364  365]]


Dari ke empat hasil yang memberikan performa terbaik adalah Logistic Regression

In [27]:
from sklearn.model_selection import GridSearchCV

param_learning = np.linspace(0.1,1,10)
param_estimator = (2,5,7,10,12)
param_grid = {'learning_rate': param_learning, 'n_estimators':param_estimator}

gs = GridSearchCV(pipe_xgb.steps[2][1],param_grid,scoring='accuracy')

# Training and searching hyper parameter space and evaluating model
# by using cross validation logic folded into 10
gs = gs.fit(X_train, y_train)

print(gs.best_score_)
print(gs.best_params_)

C:\Users\Cornelis\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.8397187196896218
{'learning_rate': 0.6, 'n_estimators': 7}


In [28]:
param_neighbors = (10,30,50,70,90)
param_grid = {'n_neighbors':param_neighbors}

gs = GridSearchCV(pipe_knn.steps[2][1],param_grid,scoring='accuracy')

# Training and searching hyper parameter space and evaluating model
# by using cross validation logic folded into 10
gs = gs.fit(X_train, y_train)

print(gs.best_score_)
print(gs.best_params_)

C:\Users\Cornelis\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.8354348528936307
{'n_neighbors': 50}


In [29]:
# param_learning = np.linspace(0.1,1,10)
param_estimator = (100,150,200)
param_grid = {'n_estimators':param_estimator}

gs = GridSearchCV(pipe_rfc.steps[2][1],param_grid,scoring='accuracy')

# Training and searching hyper parameter space and evaluating model
# by using cross validation logic folded into 10
gs = gs.fit(X_train, y_train)

print(gs.best_score_)
print(gs.best_params_)

C:\Users\Cornelis\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.831474296799224
{'n_estimators': 200}


In [30]:
import pickle

In [31]:
pickle.dump(pipe_log,open('RainAUS_predictor.sav','wb'))

In [32]:
X_test.iloc[1:3]

WindGustSpeed  Location  TempDiv  Humidity  Pressure
67598           44.0         3      4.4      68.0    1018.0
96305           24.0         0     15.3      33.0    1020.3

In [33]:
df_use['Location Name']=df1['Location']

C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [34]:
x = pipe_log.predict_proba(np.array([60,5,1000,5,4.4]).reshape(1,-1))
z =pipe_log.predict(np.array([680,150,120,5,4.4]).reshape(1,-1))
y=[]
rain_calc=[]
for i in range(2):
    y.append(round(x[0][i]*100,ndigits =2))
res = max(y)
if x[0][0]>x[0][1]:
    rain_calc.append('No')
else:
    rain_calc.append('Yes')

In [35]:
y

[0.0, 100.0]

In [36]:
df_use.sort_values(by='Location',ascending=True,axis=0,inplace=True)

C:\Users\Cornelis\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [37]:
df_use.to_csv('data_rain.csv',index=False)

In [38]:
df_use.head()

WindGustSpeed  Location  RainTomorrow  TempDiv  Humidity  Pressure  \
94366           28.0         0             0     16.8      31.0    1018.0   
95911           31.0         0             0      5.7      47.0    1031.4   
95912           48.0         0             0     11.8      40.0    1022.9   
95913           46.0         0             1      3.7      60.0    1019.4   
95914           39.0         0             0      6.8      73.0    1020.5   

      Location Name  
94366      Adelaide  
95911      Adelaide  
95912      Adelaide  
95913      Adelaide  
95914      Adelaide